services:
  backend:
    build: ./backend
    container_name: filmfund-backend
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_EMBED_MODEL=nomic-embed-text
      - OLLAMA_LLM_MODEL=qwen2.5:3b
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    restart: unless-stopped
    networks: [appnet]

  ollama:
    image: ollama/ollama:latest
    container_name: filmfund-ollama
    restart: unless-stopped
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    networks: [appnet]

  caddy:
    image: caddy:latest
    container_name: filmfund-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/srv/public
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    networks: [appnet]

volumes:
  ollama_data:
  caddy_data:
  caddy_config:

networks:
  appnet:
    driver: bridge
